# Generated by Django 3.2.16 on 2023-02-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='default_profile_picture.png', upload_to='profile_pictures/% Y/% m/% d/'),
        ),
    ]
