# Generated by Django 4.1.2 on 2022-11-27 14:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='description',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='id',
        ),
        migrations.AddField(
            model_name='notes',
            name='token_ptr',
            field=models.OneToOneField(auto_created=True, default=datetime.datetime(2022, 11, 27, 20, 25, 25, 913070), on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
