# Generated by Django 4.1.2 on 2022-11-27 16:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_remove_notes_description_remove_notes_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='token_ptr',
        ),
        migrations.AddField(
            model_name='notes',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
