# Generated by Django 4.1.2 on 2022-11-27 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('notes', '0003_remove_notes_token_ptr_notes_description_notes_uid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='uid',
        ),
        migrations.AddField(
            model_name='notes',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notes',
            name='session',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.session'),
        ),
    ]
